In [1]:
import pandas as pd

In [92]:
import random

random.seed(42)

# Sample data for generating realistic applicant records
names = [
    "Ahmed Mohamed", "Sara Ali", "Omar Hassan", "Mariam Adel",
    "Youssef Ibrahim", "Nour Khaled", "Salma Mahmoud",
    "Mostafa Samir", "Farah Tarek", "Amr Ashraf",
    "Hana Mostafa", "Karim Wael", "Aya Hossam", "Ali Gamal",
    "Malak Ahmed", "Ziad Sherif", "Nada Emad", "Khaled Fathy",
    "Jana Sameh", "Mahmoud Reda"
]

universities = [
    "Cairo University", "Ain Shams University","Helwan University", "Alexandria University",
    "Mansoura University", "BUE", "AUC",
    "Zagazig University", None, "Helwan Univ."
]

domains = [
    "Web Development", "web dev", "WEB DEV",
    "Data Science", "data science", "DATA SCIENCE",
    "AI", "Artificial Intelligence", "artificial intelligence",
    "Cyber Security", "cyber security", "Cybersecurity",
    "UI/UX", "ui/ux", "UI UX"
]

statuses = [
    "Under Review", "under review", "UNDER REVIEW",
    "Selected", "selected", "SELECTED",
    "Rejected", "rejected", "REJECTED", None
]

def random_date():
    year = random.choice([2025, 2026])
    month = random.randint(1, 12)
    day = random.randint(1, 28)

    date = pd.Timestamp(year=year, month=month, day=day)

    # Deliberately use different date formats
    if random.choice([True, False]):
         return date.strftime("%Y-%m-%d")
    return date.strftime("%d/%m/%Y")


records = []

for i in range(80):
    name = random.choice(names)
    email_name = name.lower().replace(" ", ".")
    email = f"{email_name}{i}@example.com"

    # Introduce missing values
    if random.random() < 0.07:
        name = None

    if random.random() < 0.10:
        email = None

    phone = f"01{random.randint(0, 2)}-{random.randint(10000000, 99999999)}"

    if random.random() < 0.15:
        phone = phone.replace("-", " ")

    if random.random() < 0.08:
        phone = None

    domain = random.choice(domains) 
    university = random.choice(universities)
    application_date = random_date()
    status = random.choice(statuses)

    # Introduce extra whitespace in some text values
    if name is not None and random.random() < 0.15:
        name = f" {name} "

    records.append({
        "Applicant Name": name,
        "Email": email,
        "Phone": phone,
        "Domain Applied": domain,
        "University": university,
        "Application Date": application_date,
        "Status": status
    })

df = pd.DataFrame(records)

# Ensure known duplicate examples exist
df.loc[8, "Applicant Name"] = "Ahmed Mohamed"
df.loc[8, "Email"] = "ahmed.duplicate@example.com"
df.loc[8, "Phone"] = "010-12345678"
df.loc[8, "Domain Applied"] = "Web Development"
df.loc[8, "University"] = "Cairo University"
df.loc[8, "Application Date"] = "2026-05-12"
df.loc[8, "Status"] = "Selected"

# Exact duplicate of row 9
df.iloc[9] = df.iloc[8].copy()

# Another application using the same email, with different details
df.loc[19, "Applicant Name"] = "Sara Ali"
df.loc[19, "Email"] = "sara.duplicate@example.com"
df.loc[19, "Phone"] = "010-87654321"
df.loc[19, "Domain Applied"] = "Data Science"
df.loc[19, "University"] = "Helwan University"
df.loc[19, "Application Date"] = "12/05/2026"
df.loc[19, "Status"] = "Under Review"

df.loc[20, "Applicant Name"] = " Sara Ali "
df.loc[20, "Email"] = "sara.duplicate@example.com"
df.loc[20, "Phone"] = "010 87654321"
df.loc[20, "Domain Applied"] = "data science"
df.loc[20, "University"] = "Helwan Univ."
df.loc[20, "Application Date"] = "2026-05-15"
df.loc[20, "Status"] = "under review"

# Save the raw dataset without the DataFrame index
df.to_csv("applicants.csv", index=False)

print("Dataset created successfully!")
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))
print("Columns:", df.columns.tolist())

Dataset created successfully!
Number of rows: 80
Number of columns: 7
Columns: ['Applicant Name', 'Email', 'Phone', 'Domain Applied', 'University', 'Application Date', 'Status']

In [94]:
import os

print("Current working directory:", os.getcwd())
print("CSV file exists:", os.path.exists("applicants.csv"))

df.head()

Current working directory: C:\Users\aliha
CSV file exists: True

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,None,mariam.adel0@example.com,010-28728463,UI UX,None,2025-10-14,Under Review
1,Omar Hassan,omar.hassan1@example.com,010-85329037,artificial intelligence,AUC,19/08/2025,Under Review
2,Nour Khaled,nour.khaled2@example.com,010-38898923,web dev,AUC,28/06/2025,None
3,Sara Ali,sara.ali3@example.com,011-20576383,Cyber Security,BUE,2025-12-03,Selected
4,Omar Hassan,omar.hassan4@example.com,011-47308985,WEB DEV,BUE,22/04/2026,under review

In [96]:
df = pd.read_csv("applicant_data.csv")

print("File loaded successfully:", os.path.exists("applicants.csv"))
print("Dataset shape:", df.shape)

df.head()

File loaded successfully: True
Dataset shape: (80, 7)

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,NaN,mariam.adel0@example.com,010-28728463,UI UX,NaN,2025-10-14,Under Review
1,Omar Hassan,omar.hassan1@example.com,010-85329037,artificial intelligence,AUC,19/08/2025,Under Review
2,Nour Khaled,nour.khaled2@example.com,010-38898923,web dev,AUC,28/06/2025,NaN
3,Sara Ali,sara.ali3@example.com,011-20576383,Cyber Security,BUE,2025-12-03,Selected
4,Omar Hassan,omar.hassan4@example.com,011-47308985,WEB DEV,BUE,22/04/2026,under review

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    77 non-null     object
 1   Email             69 non-null     object
 2   Phone             77 non-null     object
 3   Domain Applied    80 non-null     object
 4   University        69 non-null     object
 5   Application Date  80 non-null     object
 6   Status            70 non-null     object
dtypes: object(7)
memory usage: 4.5+ KB

In [22]:
df.isnull().sum()

Applicant Name       3
Email               11
Phone                3
Domain Applied       0
University          11
Application Date     0
Status              10
dtype: int64

In [26]:
df.duplicated().sum()

1

In [84]:
# Count missing applicant names before handling them
print("Missing names before:", df["Applicant Name"].isnull().sum())

# Remove rows with missing applicant names
df = df.dropna(subset=["Applicant Name"])

print("Missing names after:", df["Applicant Name"].isnull().sum())
print("Dataset shape after dropping rows:", df.shape)

Missing names before: 3
Missing names after: 0
Dataset shape after dropping rows: (77, 7)

In [30]:
# Count missing emails before handling them
print("Missing emails before:", df["Email"].isnull().sum())

# Fill missing email addresses with a placeholder
df["Email"] = df["Email"].fillna("not_provided@example.com")

print("Missing emails after:", df["Email"].isnull().sum())

Missing emails before: 11
Missing emails after: 0

In [32]:
print("Missing universities before:", df["University"].isnull().sum())
df["University"] = df["University"].fillna("Not Specified")
print("Missing universities after:", df["University"].isnull().sum())

Missing universities before: 10
Missing universities after: 0

In [34]:

print("Missing statuses before:", df["Status"].isnull().sum())
df["Status"] = df["Status"].fillna("Under Review")
print("Missing statuses after:", df["Status"].isnull().sum())

Missing statuses before: 8
Missing statuses after: 0

In [36]:

print("Dataset shape:", df.shape)
print("\nMissing values after Step 4:")
print(df.isnull().sum())
print("\nTotal missing values:")
print(df.isnull().sum().sum())

Dataset shape: (77, 7)

Missing values after Step 4:
Applicant Name      0
Email               0
Phone               3
Domain Applied      0
University          0
Application Date    0
Status              0
dtype: int64

Total missing values:
3

In [38]:

# Remove exact duplicate rows
df = df.drop_duplicates()

# Verify the result
print("Dataset shape after removing exact duplicates:", df.shape)
print("Remaining exact duplicates:", df.duplicated().sum())

Dataset shape after removing exact duplicates: (76, 7)
Remaining exact duplicates: 0

In [40]:

# Checking Duplicate Applications by Email
# I checked for duplicate applications using Email as an applicant
# identifier because the same applicant may submit multiple applications with slightly different details.
# I excluded the placeholder email "not_provided@example.com"
# because it does not identify a specific applicant.

# Exclude placeholder emails
valid_email = df["Email"] != "not_provided@example.com"

# Find all records with repeated valid email addresses
duplicate_emails = df.loc[
    valid_email & df["Email"].duplicated(keep=False)
].sort_values("Email")

print("Records with duplicate valid emails:", len(duplicate_emails))
print("Additional duplicate applications:",
      df.loc[valid_email, "Email"].duplicated().sum())

duplicate_emails

Records with duplicate valid emails: 2
Additional duplicate applications: 1

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
19,Sara Ali,sara.duplicate@example.com,010-87654321,Data Science,Helwan University,12/05/2026,Under Review
20,Sara Ali,sara.duplicate@example.com,010 87654321,data science,Helwan Univ.,2026-05-15,under review

In [42]:
# Remove duplicate applications based on valid emails
duplicate_mask = (
    df["Email"].ne("not_provided@example.com")
    & df["Email"].duplicated()
)

df = df.loc[~duplicate_mask].copy()

# Verify the results
print("Dataset shape:", df.shape)
print("Remaining exact duplicates:", df.duplicated().sum())

Dataset shape: (75, 7)
Remaining exact duplicates: 0

In [44]:
df["Domain Applied"].unique()

array(['artificial intelligence', 'web dev', 'Cyber Security', 'WEB DEV',
       'Cybersecurity', 'UI UX', 'Artificial Intelligence',
       'Web Development', 'AI', 'DATA SCIENCE', 'data science',
       'Data Science', 'ui/ux', 'UI/UX', 'cyber security'], dtype=object)

In [46]:

# Remove extra whitespace and standardize casing
df["Domain Applied"] = df["Domain Applied"].str.strip().str.lower()

In [48]:
# Standardize domain names
domain_mapping = {
    "web dev": "Web Development", "web development": "Web Development",
    "data science": "Data Science",
    "ai": "Artificial Intelligence", "artificial intelligence": "Artificial Intelligence",
    "cyber security": "Cyber Security", "cybersecurity": "Cyber Security",
    "ui ux": "UI/UX", "ui/ux": "UI/UX"
}

df["Domain Applied"] = df["Domain Applied"].map(domain_mapping)

df["Domain Applied"].unique()

array(['Artificial Intelligence', 'Web Development', 'Cyber Security',
       'UI/UX', 'Data Science'], dtype=object)

In [50]:
df["Status"] = df["Status"].str.strip().str.title()
df["Status"].unique()

array(['Under Review', 'Selected', 'Rejected'], dtype=object)

In [70]:
# Remove extra whitespace from all text columns
for col in df.select_dtypes(include=["object", "string"]).columns:
    df[col] = df[col].str.strip()

In [54]:

print("Domains:", df["Domain Applied"].nunique())
print("Statuses:", df["Status"].unique())
print("Missing values:\n", df.isnull().sum())

Domains: 5
Statuses: ['Under Review' 'Selected' 'Rejected']
Missing values:
 Applicant Name      0
Email               0
Phone               3
Domain Applied      0
University          0
Application Date    0
Status              0
dtype: int64

In [58]:

df["Application Date"] = pd.to_datetime(
    df["Application Date"], errors="coerce", dayfirst=True
)

df["Application Date"].isnull().sum()

35

In [98]:

# Restore original dates for the remaining rows
raw_dates = pd.read_csv("applicants.csv")["Application Date"]
df["Application Date"] = raw_dates.loc[df.index]

# Parse mixed date formats
df["Application Date"] = pd.to_datetime(
    df["Application Date"], format="mixed",
    dayfirst=True, errors="coerce"
)

print("Missing dates:", df["Application Date"].isnull().sum())
print("Date type:", df["Application Date"].dtype)

Missing dates: 0
Date type: datetime64[ns]

In [62]:
df["Phone"] = df["Phone"].str.replace(r"[-\s]", "", regex=True)
df["Phone"].head()

1    01085329037
2    01038898923
3    01120576383
4    01147308985
5    01160929647
Name: Phone, dtype: object

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 75 entries, 1 to 79
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    75 non-null     object
 1   Email             75 non-null     object
 2   Phone             72 non-null     object
 3   Domain Applied    75 non-null     object
 4   University        75 non-null     object
 5   Application Date  75 non-null     datetime64[ns]
 6   Status            75 non-null     object
dtypes: datetime64[ns](1), object(6)
memory usage: 4.7+ KB

In [88]:

df.to_csv("applicants_cleaned.csv", index=False)

In [100]:

print(os.path.exists("applicants_cleaned.csv"))

True